/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/book.glb 
Author: Världskulturmuseerna (https://sketchfab.com/varldskulturmuseerna)
License: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
Source: https://sketchfab.com/3d-models/coptic-prayer-book-500ec4621d764f0dadb8edc93b8700ae
Title: Coptic prayer book
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/book.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-0.818, -0.112, 0.082]} scale={100}>
        <mesh geometry={nodes.Model_material0_0.geometry} material={materials.material0} />
        <mesh geometry={nodes.Model_material0_0_1.geometry} material={materials.material0} />
      </group>
    </group>
  )
}

useGLTF.preload('/book.glb')
